apiVersion: v1
kind: Service
metadata:
  name: customer-support-service
  namespace: application
spec:
  selector:
    app: customer-support
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
