# infrastructure/database/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jalbritt/customer-service-automation/infrastructure.git'
    targetRevision: HEAD
    path: database
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

