apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: infrastructure
    repoURL: https://github.com/jalbritt/customer-service-automation/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
