apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"  # Example cookie, should be secure
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
